POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Raicy01",
    "password": "1234"
}

###
POST http://localhost:5000/api/auth/login 
Content-Type: application/json

{
    "username": "mirai210",
    "password": "1234"
}

###
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI1OGQzZDIzNzFkZGVmYzdhZjdiODAiLCJpYXQiOjE2NjM0MDUzNzN9.RmggUYgfZAzcak7ih43P4DKmm8HL36bYP6mVA46ynQk

{
    "title": "my first post",
    "description": "abc",
    "url": "google.com",
    "status": "LEARNING"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI0OGM5N2YyZWNlOTdiYjE2MjZlOWIiLCJpYXQiOjE2NjM0MDU3ODd9.81M7h687Zq1TYf0eKz4BacWGCzV1Aio3TQkuhmWnrDQ

###
PUT http://localhost:3000/api/posts/6324a3d44b30357aa9c3f9d7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI0OGM5N2YyZWNlOTdiYjE2MjZlOWIiLCJpYXQiOjE2NjM0MDU3ODd9.81M7h687Zq1TYf0eKz4BacWGCzV1Aio3TQkuhmWnrDQ

{
    "title": "vueJs", 
    "description": "VUE FRONTEND",
    "url": "vue.org",
    "status": "LEARNING"
}

###
DELETE http://localhost:3000/api/posts/6324a3d44b30357aa9c3f9d7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI0OGM5N2YyZWNlOTdiYjE2MjZlOWIiLCJpYXQiOjE2NjM0MDU3ODd9.81M7h687Zq1TYf0eKz4BacWGCzV1Aio3TQkuhmWnrDQ

###
POST http://localhost:5000/api/products
Content-Type: application/json

{
    "productname": "Túi đựng Airpods 3 Native Union Nhựa dẻo",
    "price":  350000,
    "saleoff": 0,
    "color": ["black", "pink"],
    "productimage": [
        "https://cdn.tgdd.vn/Products/Images/7925/270058/tui-dung-airpods-3-native-union-nhua-deo-xanh-1.jpg",
        "https://cdn.tgdd.vn/Products/Images/7925/270058/tui-dung-airpods-3-native-union-nhua-deo-xanh-2.jpg",
        "https://cdn.tgdd.vn/Products/Images/7925/270058/tui-dung-airpods-3-native-union-nhua-deo-xanh-3.jpg",
        "https://cdn.tgdd.vn/Products/Images/7925/270058/tui-dung-airpods-3-native-union-nhua-deo-1.jpg",
        "https://cdn.tgdd.vn/Products/Images/7925/270058/tui-dung-airpods-3-native-union-nhua-deo-2.jpg",
        "https://cdn.tgdd.vn/Products/Images/7925/270058/tui-dung-airpods-3-native-union-nhua-deo-3.jpg"
    ],
    "description": "Đặc điểm nổi bậtSản phẩm chuyên dụng cho dòng AirPods 3.Túi đựng nhỏ gọn, ôm sát AirPods bên trong, không chiếm diện tích khi cất giữ.Màu sắc thời thượng, chất liệu nhựa dẻo vừa bền bỉ vừa mềm mại, dẻo dai.Bảo vệ AirPods bên trong không bị bám dính bụi bẩn và trầy xước.",
    "category": "PHỤ KIỆN",
    "state": "STOCKING",
    "firm": "635d489e9c0ec0bdb0b88931"
}

###
GET http://localhost:5000/api/products/635d376b3e4b44f29f616f40


###
GET http://localhost:5000/api/products/category/dien-thoai

###
GET http://localhost:5000/api/products/search/iPhonesadsa

### 
POST http://localhost:5000/api/comments/635d4d60242c2561153a6315
Content-Type: application/json

{
    "content": "sản phẩm chất lượng dùng oke lắm shop",
    "username": "Truong Van Hao",
    "email": "truongvanhao159@gmail.com",
    "idproduct": "635d4d60242c2561153a6315"
}

### 
GET http://localhost:5000/api/comments/635d4d60242c2561153a6315